/* $Id$ */

package org.p2presenter.instructor.ui.event;

/** Convenience listener that ignores events generated by a particular source.
 * @author Ryan Berdeen
 *
 * @param <T>
 */
public abstract class ListenerAdaptor<T extends Event> implements Listener<T> {
	private Object source;
	
	/** 
	 * @param source the source for which to ignore events.
	 */
	public ListenerAdaptor(Object source) {
		this.source = source;
	}

	public final void onEvent(T event) {
		if (source != event.getSource()) {
			onExternalEvent(event);;
		}
	}

	/** Called only when the source of the event is not the source being ignored.
	 */
	public abstract void onExternalEvent(T event);
}
